apiVersion: apps/v1
kind: Deployment
metadata:
  name: page1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page1-app
  template:
    metadata:
      labels:
        app: page1-app
    spec:
      containers:
      - name: page1-container
        image: francisgrane/page1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: page1-service
spec:
  selector:
    app: page1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000   # Define the NodePort here
  type: NodePort        # Change the type to NodePort
