apiVersion: apps/v1
kind: Deployment
metadata:
  name: page2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page2-app
  template:
    metadata:
      labels:
        app: page2-app
    spec:
      containers:
      - name: page2-container
        image: francisgrane/page2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: page2-service
spec:
  selector:
    app: page2-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001   # Define the NodePort here
  type: NodePort        # Change the type to NodePort
